version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_aggregation
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d data_aggregation"]
      interval: 3s
      timeout: 3s
      retries: 5

  migrator:
    build: .
    command: ["/bin/migrator"]
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    command: ["/bin/app"]
    ports:
      - "8080:8080"
    volumes:
      - ./local.env:/app/local.env
      - ./config/local.yaml:/app/local.yaml
    depends_on:
      migrator:
        condition: service_completed_successfully
